### ISSUE TITLE
Bitrate in results

### ISSUE THREAD

**Issue by aeyoll** [f-hj/slsk-client#1]
Hello,
First of all, this is nice to see a client for the glorious Soulseek, thanks a lot for your work!

I was wondering if there was any way to fetch the bitrate of the mp3 files in the results, as in the official client. It would be useful to filter the results for example.

Thanks a lot

**Comment by f-hj** [comment]
Hello,
Thank you very much for using this module. Now bitrate is sent with result in version 1.0.4, this version is published in NPM.

Don't hesitate if you need anything else,
Have fun,
Xo
