### ISSUE TITLE
Any idea when downloadStream() is going to be completed?

### ISSUE THREAD

**Issue by riteable** [f-hj/slsk-client#3]
I think `downloadStream()` is the only major function missing from this package at the moment. I'm eager to build an app, but without a streaming option it's hard to build a user friendly experience.

So, any idea when this will be implemented?

**Comment by f-hj** [comment]
Hi!

Now `downloadStream()` is implemented in `v1.0.5`, I did it very quickly and I'll wait the complete refactor to have a better way to handle all errors, maybe this or next week.
If you have any problem, please open a new issue.

Thank you for using this module,
Have a nice day!

**Comment by riteable** [comment]
Wow, you're awesome. Thanks!
