### ISSUE TITLE
extra options on search method?

### ISSUE THREAD

**Issue by hems** [f-hj/slsk-client#34]
I'm trying to find out what options are available when searching but i can't find documentation.

Currently, https://www.museek-plus.org/wiki/SoulseekProtocol is not online anymore so i'm wondering if you have a backup or an updated link to the protocol documentation?

Thank You

**Comment by andreabertagnolli** [comment]
you can use wayback machine:
https://web.archive.org/web/20190222204821/https://www.museek-plus.org/wiki/SoulseekProtocol

but... yes, I think could be a right moment to create an updated, comprehensive documentation of the protocol

**Comment by hems** [comment]
Indeed, would be nice to create an HTTP layer on top with express so an HTML application on the browser would be able to interface / communicate with the client installed locally, this would open a lot of nice possibilities!

**Comment by hems** [comment]
I can't find an extra option field for the search method, so i believe the only way is by manually filtering the results..

I wonder who the QT app does... they probably build the file list on the client side and then filter the results on the client side as well... ?

**Comment by f-hj** [comment]
Yep, the QT app is filtering on client side.
There is no way to do it before receiving results https://www.museek-plus.org/wiki/SoulseekProtocol#PeerCode8

**Comment by hems** [comment]
that's awesome, thanks a lot guys!
